title: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: ""
url: "" 
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock