title: 
email: 
description: "One of the most reliable Paphos property development companies. It has become synonymous with quality, honesty, reliability and timely delivery, as well as guaranteed title deeds."
  
baseurl: ""
url: "" 
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock